package com.rodrigodev.xgen.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames_specialCases.error_name1.error_name2.error_name3_2_;

import com.rodrigodev.xgen.test.organization.packages.packagesForErrorsAreGeneratedFromErrorNames_specialCases.error_name1.error_name2.ErrorName2Exception;

/**
* Autogenerated by XGen on July 1, 2015.
*/
public class Error_Name3_2_Exception extends ErrorName2Exception {

    protected Error_Name3_2_Exception(String message) {
        super(message);
    }
}
