package com.rodrigodev.xgen4j_table_generator.test.tableIsGeneratedForErrorsWithNumericId.cname1.cname2.cname3_2;

import com.rodrigodev.xgen4j_table_generator.test.tableIsGeneratedForErrorsWithNumericId.cname1.cname2.CName2Error;

import java.lang.String;
import java.lang.Integer;
import com.rodrigodev.xgen4j.test.common.doubles.error.message.TestObject;

import com.rodrigodev.xgen4j_table_generator.test.tableIsGeneratedForErrorsWithNumericId.ErrorCode;
import com.rodrigodev.xgen4j_table_generator.test.tableIsGeneratedForErrorsWithNumericId.RootNameException;
import com.rodrigodev.xgen4j_table_generator.test.tableIsGeneratedForErrorsWithNumericId.RootNameException.ExceptionType;

/**
 * Autogenerated by XGen on January 1, 0001.
 */
public abstract class CName3_2Error extends CName2Error {

    public static final ErrorCode CODE = new ErrorCode("common-code-name-3-2", 5, CName2Error.CODE);

    private static String MESSAGE_FORMAT = "CName3_2: {param1: '%s', param2: %d, param3: '%s'}";

    private static String createMessage(String param1, Integer param2, TestObject param3) {
        if(param1 == null) throw new NullPointerException("param1");
        if(param2 == null) throw new NullPointerException("param2");
        if(param3 == null) throw new NullPointerException("param3");

        return String.format(MESSAGE_FORMAT, param1, param2, param3);
    }

    public static void throwException(String param1, Integer param2, TestObject param3) {
        throw new CName3_2Exception(createMessage(param1, param2, param3));
    }

    public static void throwException(String param1, Integer param2, TestObject param3, Throwable cause) {
        throw new CName3_2Exception(createMessage(param1, param2, param3), cause);
    }

    public static void throwException(ExceptionType exceptionType, String param1, Integer param2, TestObject param3) {
        throwExceptionForCommonError(exceptionType, createMessage(param1, param2, param3));
    }

    public static void throwException(ExceptionType exceptionType, String param1, Integer param2, TestObject param3, Throwable cause) {
        throwExceptionForCommonError(exceptionType, createMessage(param1, param2, param3), cause);
    }

}
